# Usa la imagen base de PostgreSQL
FROM postgres:17

# Instalar dependencias necesarias para compilar pgaudit
RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    libpq-dev \
    postgresql-server-dev-17

# Clonar e instalar pgaudit
RUN git clone https://github.com/pgaudit/pgaudit.git /pgaudit && \
    cd /pgaudit && \
    make && \
    make install && \
    rm -rf /pgaudit

# Hacer que pgaudit se cargue automáticamente en PostgreSQL
RUN echo "shared_preload_libraries = 'pgaudit'" >> /usr/share/postgresql/postgresql.conf.sample

# Comando por defecto para iniciar PostgreSQL
CMD ["postgres"]
